caldera:
  base: "http://localhost:8888"   # Caldera base URL (use localhost if running on same VM)
  api_key: ""                     # if required, else leave blank

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "YOUR_NEO4J_PASSWORD"

ranking:
  method: "wsm"
  weight_source: "uniform" # uniform | frequency | explicit
  # explicit weights example:
  # technique_weights:
  #   "T1082": 0.2
  #   "T1016": 0.3
  #   "T1059": 0.5
